[package]
name = "rust2go-cli"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
cbindgen = "0.26"
rust2go = { path = "../rust2go", features = ["gen"] }

[[bin]]
name = "rust2go"
path = "src/main.rs"
